web:
  config:
    maxAge: 3600
    allowedOrigins: http://localhost:8082

server:
  port: 8800
  servlet:
    context-path: /manage


spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: mama0927
    username: root
    url: jdbc:mysql://127.0.0.1:3306/study?serverTimezone=GMT&characterEncoding=utf8&useSSL=false
#mybatis
mybatis:
  type-aliases-package: com.manage.frame.entity.dao
  mapper-locations: classpath:mapper/*.xml

logging:
  path: log/
  file: manage.log
